In [1]:
from scipy import linalg
import numpy as np

In [47]:
M11 = 86.80879
M33 = 86.80879
M55 = 86.80879*0.782**2

#T=3
A11 = 2 
A33 = 223
A55 = 137
# B11 = 0.28
B11 = 12
B33 = 386
B55 = 18.4

C11 = 0
C33 = 11014
C55 = 6233

In [48]:
a = np.array([[0, 1], [-C11/(M11+A11), -B11/(M11+A11)]])
b = np.array([[1/B11], [1/(M11+A11)]])
q = 1000*np.array([[1, 0], [0, 10000]])
r = 1
p = linalg.solve_continuous_are(a,b,q,r)
p

array([[  46464.73208447, -341064.67231491],
       [-341064.67231491, 2784043.99702716]])

In [49]:
a

array([[ 0.        ,  1.        ],
       [ 0.        , -0.13512176]])

In [50]:
b.T

array([[0.08333333, 0.01126015]])

In [51]:
p

array([[  46464.73208447, -341064.67231491],
       [-341064.67231491, 2784043.99702716]])

In [52]:
0.28060176*3.57142857 - 0.01126015*0.19086265

1.0000000003878857

In [53]:
np.matmul(b.T,p)

array([[  31.6227766 , 2926.68768513]])

In [54]:
b.T * p

array([[  3872.06100704,  -3840.43823044],
       [-28422.05602624,  31348.74371137]])

In [55]:
(b.T @ p).shape

(1, 2)

In [57]:
x = np.array([0.01,0.05])
F = -1/r * b.T @ p @ x
F[0]

-146.65061202256624