In [1]:
from scipy import linalg
import numpy as np

In [25]:
M11 = 86.80879
M33 = 86.80879
M55 = 86.80879*0.782**2

#T=3
A11 = 2 
A33 = 223
A55 = 137
# B11 = 0.28
B11 = 12
B33 = 386
B55 = 18.4

C11 = 0
C33 = 11014
C55 = 6233

In [26]:
a = np.array([[0, 1], [-C11/(M11+A11), -B11/(M11+A11)]])
b = np.array([[1/B11], [1/(M11+A11)]])
q = 1000*np.array([[1, 0], [0, 1]])
r = 1
p = linalg.solve_continuous_are(a,b,q,r)
p

array([[ 396.8390061 , -128.51880324],
       [-128.51880324, 2114.37767771]])

In [27]:
a

array([[ 0.        ,  1.        ],
       [ 0.        , -0.13512176]])

In [28]:
b.T

array([[0.08333333, 0.01126015]])

In [29]:
p

array([[ 396.8390061 , -128.51880324],
       [-128.51880324, 2114.37767771]])

In [30]:
0.28060176*3.57142857 - 0.01126015*0.19086265

1.0000000003878857

In [31]:
np.matmul(b.T,p)

array([[31.6227766 , 13.09830247]])

In [32]:
b.T * p

array([[ 33.06991717,  -1.44714057],
       [-10.70990027,  23.80820274]])

In [33]:
(b.T @ p).shape

(1, 2)

In [35]:
x = np.array([0.1,0.25])
F = -1/r * b.T @ p @ x
F

array([-6.43685328])